# Generated by Django 5.1.7 on 2025-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('Weddings', 'weddings'), ('Engagements', 'engagements'), ('Portraits', 'portraits')], max_length=30),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Weddings', 'weddings'), ('Engagements', 'engagements'), ('Portraits', 'portraits')], max_length=30),
        ),
    ]
