# Generated by Django 5.1.7 on 2025-03-19 14:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_faq_alter_client_category_alter_portfolio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_5', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_6', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_7', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
