# Generated by Django 5.1.7 on 2025-03-23 15:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_home_engagement_img_home_portrait_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='engagement_img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='engagement_image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_5',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_5'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_6',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_6'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_7',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_7'),
        ),
        migrations.AlterField(
            model_name='home',
            name='portrait_img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='portrait_image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='wedding_img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='wedding_image'),
        ),
    ]
