# Generated by Django 5.1.7 on 2025-03-23 16:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_home_engagement_img_alter_home_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='main_img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='main_img'),
        ),
        migrations.AddField(
            model_name='about',
            name='top_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='top_image'),
        ),
    ]
