# Generated by Django 5.1.7 on 2025-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_client_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Weddings', 'weddings'), ('Engagements', 'engagements'), ('Portraits', 'portraits'), ('Kids and Family', 'kids and family'), ('Products and Lifestyle', 'products and lifestyle')], max_length=30),
        ),
    ]
