# Generated by Django 5.1.7 on 2025-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('Weddings', 'weddings'), ('Engagements', 'engagements'), ('Portraits', 'portraits'), ('Children and Family', 'children and family'), ('Products and Lifestyle', 'products and lifestyle')], max_length=30),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Weddings', 'weddings'), ('Engagements', 'engagements'), ('Portraits', 'portraits'), ('Children and Family', 'children and family'), ('Products and Lifestyle', 'products and lifestyle')], max_length=30),
        ),
    ]
