# Generated by Django 5.1.7 on 2025-03-28 09:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_client_category_alter_portfolio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('thumbmail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='thumbmail')),
                ('content', models.TextField()),
            ],
        ),
    ]
